tracert www.infraero.gov.br > trace_brasil_sur.txt
tracert www.unirio.br >> trace_brasil_sur.txt
tracert www.santosfc.com.br >> trace_brasil_sur.txt
tracert www.rio.rj.gov.br >> trace_brasil_sur.txt
tracert www.rj.gov.br >> trace_brasil_sur.txt
tracert www.cgu.gov.br >> trace_brasil_sur.txt
tracert www.fazenda.rj.gov.br >> trace_brasil_sur.txt
tracert www.riocapitaldaenergia.rj.gov.br >> trace_brasil_sur.txt
tracert www.santos.sp.gov.br >> trace_brasil_sur.txt
tracert www.turismosantos.com.br >> trace_brasil_sur.txt
tracert www.praiagrande.sp.gov.br >> trace_brasil_sur.txt
tracert www.guaruja.sp.gov.br >> trace_brasil_sur.txt
tracert www.guaruja.com.br >> trace_brasil_sur.txt