tracert www.presidencia.gub.uy > enlace_bicentenario_trace_incomplete.txt
tracert www.onsc.gub.uy >> enlace_bicentenario_trace_incomplete.txt
tracert www.ine.gub.uy >> enlace_bicentenario_trace_incomplete.txt
tracert www.ursec.gub.uy >> enlace_bicentenario_trace_incomplete.txt
tracert www.mdn.gub.uy >> enlace_bicentenario_trace_incomplete.txt
tracert www.mef.gub.uy >> enlace_bicentenario_trace_incomplete.txt
tracert www.mec.gub.uy >> enlace_bicentenario_trace_incomplete.txt
tracert www.miem.gub.uy >> enlace_bicentenario_trace_incomplete.txt
tracert www.mrree.gub.uy >> enlace_bicentenario_trace_incomplete.txt
tracert www.montevideo.gub.uy >> enlace_bicentenario_trace_incomplete.txt
tracert www.rivera.gub.uy >> enlace_bicentenario_trace_incomplete.txt
tracert www.ort.edu.uy >> enlace_bicentenario_trace_incomplete.txt
tracert www.ucu.edu.uy >> enlace_bicentenario_trace_incomplete.txt
tracert portal.fagro.edu.uy >> enlace_bicentenario_trace_incomplete.txt