tracert www2.opp.gub.uy > enlace_bicentenario_trace_complete.txt
tracert www.artigas.gub.uy >> enlace_bicentenario_trace_complete.txt
tracert www.imf.gub.uy >> enlace_bicentenario_trace_complete.txt
tracert www.paysandu.gub.uy >> enlace_bicentenario_trace_complete.txt
tracert www.soriano.gub.uy >> enlace_bicentenario_trace_complete.txt
tracert www.universidad.edu.uy >> enlace_bicentenario_trace_complete.txt
tracert www.fcien.edu.uy >> enlace_bicentenario_trace_complete.txt
tracert www.fmed.edu.uy >> enlace_bicentenario_trace_complete.txt
tracert www.utu.edu.uy >> enlace_bicentenario_trace_complete.txt
tracert www.fcs.edu.uy >> enlace_bicentenario_trace_complete.txt
tracert www.comunicacion.edu.uy >> enlace_bicentenario_trace_complete.txt
tracert www.isef.edu.uy >> enlace_bicentenario_trace_complete.txt
tracert www.iesta.edu.uy >> enlace_bicentenario_trace_complete.txt